### ISSUE TITLE
Crashes if there are lots of objects in a document

### ISSUE THREAD

**Issue by bjoernm** [Raureif/sketch-click-dummy#3]
This is an awesome plugin and something I was looking forward to for a long time! However, I cannot fix the problem that Sketch crashes with when there are lots of objects on a page / document, even if I try to remove everything unnecessary.

Any ideas what the problem could be? I have read about several other plugins that they also crash if there are too many objects.

I know that you listed it under "Known Issues" but maybe there is a way to fix it.

**Comment by Raureif** [comment]
Thanks! We know this limitation is annoying. We agree, it must be some kind of memory issue in Sketch’s plugin interface that is related to the number of objects on the current page.
The workaround we currently use is splitting the document into multiple pages (like 1 or 2 artboards per page).

If you want to help, you may want to report this bug to the Sketch team.

**Comment by leo** [comment]
This could help: https://github.com/preciousforever/sketch-toggle-layer-visibility/issues/2#issuecomment-71492382

**Comment by frankrausch** [comment]
Looks good. Thanks.

**Comment by frankrausch** [comment]
Is this still an issue? Then please let me know and I’ll reopen the issue.
