### ISSUE TITLE
crash during exporting: authorize of target folder Documents fails / target folder isn't respected

### ISSUE THREAD

**Issue by PeterEmil** [Raureif/sketch-click-dummy#4]
When exporting a file (in my case just the `Click Dummy Example.sketch`) to the Documents folder Sketch crashes. When exporting to a different folder on a external harddrive export succeeds, but the exported click dummy is placed within the plugins folder instead of chosen folder on external harddrive... after this first attempt the plugin only outputs its export into the plugins folder.

**Comment by Raureif** [comment]
Oh yeah, that’s confusing:
The exported folder is always placed in the parent folder of the Sketch document.
You must authorize the parent folder of the Sketch document (due to Apple’s app sandboxing).

**Comment by PeterEmil** [comment]
So I can't choose a target folder? Better to remove that option and solely create the alert for authorization  then. Nice plugin though!

**Comment by Raureif** [comment]
Exactly. Thanks.
