### ISSUE TITLE
Export broken in 3.2.2?

### ISSUE THREAD

**Issue by filtercake** [Raureif/sketch-click-dummy#6]
When I open the example file in Sketch 3.2.2, "Export Click Dummy" seems to do nothing. There is no dialog, neither can I find the Clickdummy somewhere on the disk.

Am on OS X 10.10.2 – need any other info?

**Comment by Raureif** [comment]
Please check the folder where the Sketch file sits. There will be a new folder with the name of your Sketch file that contains the HTML click dummy.
If you’ve opened the example file from the plugins folder, please look there.

**Comment by filtercake** [comment]
> Please check the folder where the Sketch file sits. There will be a new folder with the name of your Sketch file that contains the HTML click dummy.

No, there isn't.

> If you’ve opened the example file from the plugins folder, please look there.

I did, there isn't.

If you cannot reproduce the bug, would you have hint what could be wrong with my configuration?

**Comment by Raureif** [comment]
Are you using the App Store version of Sketch?

Please try putting the Example .sketch file on you Desktop and then run the plugin.

**Comment by Raureif** [comment]
Try putting the plugin’s JS files right in the plugins folder.
Someone told us it worked for them:
https://github.com/Raureif/sketch-click-dummy/issues/7#issuecomment-81764502
