### ISSUE TITLE
Can't find exported file. Is it exported?

### ISSUE THREAD

**Issue by Magnus-G** [Raureif/sketch-click-dummy#7]
I'm using Sketch 3.2.2 and I can't seem to find the location for the exported HTML file. Or it doesn't seem to export properly. The plugin is installed correctly and shows up in the dropdown and all but I can't see the exported HTML. Please help!

**Comment by Raureif** [comment]
Please check whether this solves your problem: https://github.com/Raureif/sketch-click-dummy/issues/6

If not:
Do you have the Mac App Store version of Sketch? May be an issue with sandboxing …

**Comment by Magnus-G** [comment]
Hey! It works! I didn't know I had to put the js files in the plugins folder but after I did so it worked great. Thank you!

**Comment by Magnus-G** [comment]
This workflow seems extremely handy! Thanks again.

**Comment by Raureif** [comment]
You mean you had to put the JS files right in the root of the plugins folder? You could not leave them in a subfolder?

**Comment by Magnus-G** [comment]
Seems like I have to have them in the root of the plugins folder, yes.

**Comment by Raureif** [comment]
Strange. Thanks for the info.
