### ISSUE TITLE
hideLinkLayers and showLinkLayers

### ISSUE THREAD

**Issue by edverillo** [Raureif/sketch-click-dummy#8]
I have commented the hideLinkLayers() and showLinkLayers() calls in Export Click Dummy.sketchplugin and my crashes have stopped. I did not go into further debugging, but I believe they might be the cause for these crashes.

**Comment by Raureif** [comment]
Thanks for the comment.
These function calls are there for a reason though: They temporarily hide the link layers (as the function name suggests). Without these calls, the exported PNGs may contain the link layers.

Of course, you can also use the plugin’s separate menu entries to hide/show these layers.
Or you can use transparent link layers.

**Comment by edverillo** [comment]
I has started crashing again after I added a couple more artboards. I would love to help, when I find some time. It is a great idea and I could see myself using it a lot.
